services:
  proxy:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./docker/proxy/servers.conf:/etc/nginx/conf.d/servers.conf
  app-franken:
    build:
      context: .
      dockerfile: ./docker/franken/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./app:/app
    # command: "tail -f /dev/null"
  app-swoole:
    build:
      context: .
      dockerfile: ./docker/swoole/Dockerfile
    ports:
      - "8001:80"
    volumes:
      - ./app:/app
    # command: "tail -f /dev/null"
  app-roadrunner:
    build:
      context: .
      dockerfile: ./docker/roadrunner/Dockerfile
    ports:
      - "8002:8000"
    volumes:
      - ./app:/app
    # command: "tail -f /dev/null"
  app-nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "8003:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/fpm/Dockerfile
    volumes:
      - ./app:/var/www

  db:
    container_name: db
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=wrgs2703
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=wrgs2703
      - MYSQL_DATABASE=laravel
